version: '3.7'
services:
  coredns:
    image: kcr.khalti.com.np/opstool/coredns-prod:latest-${DATACENTER}
    hostname: coredns-{{.Task.Slot}}
    ports:
      - 53:53/udp
    networks:
      - coredns
    deploy:
      mode: global
      labels:
        environment: "prod"
        project: coredns
        app_layer: "infra"
      resources:
        limits:
          cpus: '2'
          memory: '4G'

networks:
  coredns:
    name: coredns
    driver: overlay
    ipam:
      config:
        - subnet: 10.203.3.64/26

